# Generated by Django 5.1.6 on 2025-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('citizen_name', models.CharField(max_length=200)),
                ('citizen_password', models.CharField(max_length=200)),
                ('citizen_address', models.CharField(max_length=400)),
                ('citizen_email', models.EmailField(max_length=254)),
                ('citizen_phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('investigator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('investigator_name', models.CharField(max_length=200)),
                ('investigator_password', models.CharField(max_length=200)),
                ('investigator_address', models.CharField(max_length=400)),
                ('investigator_email', models.EmailField(max_length=254)),
                ('investigator_phone_number', models.IntegerField()),
            ],
        ),
    ]
