# Generated by Django 5.1.6 on 2025-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_delete_investigator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('investigator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('investigator_name', models.CharField(max_length=200)),
                ('investigator_password', models.CharField(max_length=200)),
                ('investigator_address', models.CharField(max_length=400)),
                ('investigator_email', models.EmailField(max_length=254)),
                ('investigator_phone_number', models.IntegerField()),
            ],
        ),
    ]
