# Generated by Django 5.1.6 on 2025-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='citizen_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ReportEaseApp/static/ProfilePics'),
        ),
    ]
