# Generated by Django 5.1.6 on 2025-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_citizen_citizen_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/ASUS/OneDrive/Documents/notes sixth sem/project/Project Code/ReportEase/ReportEaseApp/static/ReportEaseApp/ProfilePics'),
        ),
    ]
