# Generated by Django 5.1.6 on 2025-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_citizen_citizen_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ReportEaseApp/static/ReportEaseApp/ProfilePics'),
        ),
    ]
