# Generated by Django 5.1.6 on 2025-02-23 13:57

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_citizen_citizen_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_profile_pic_path),
        ),
    ]
