# Generated by Django 5.1.6 on 2025-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_rename_citizen_address_citizen_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='user_district',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
