# Generated by Django 5.1.6 on 2025-04-12 06:33

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_investigator_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.Investigator_profile_pic_path),
        ),
    ]
