# Generated by Django 5.1.6 on 2025-04-14 09:43

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_investigator_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='user_citizenship',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_citizenship_pic_path),
        ),
    ]
