# Generated by Django 5.1.6 on 2025-04-14 09:45

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_citizen_user_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='user_recent_photo',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_recent_pic_path),
        ),
    ]
