# Generated by Django 5.2 on 2025-04-27 13:48

import django.db.models.deletion
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_citizen_user_recent_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='citizen_recent_photo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userauths.citizen')),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_recent_pic_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='user_recent_photo',
        ),
    ]
