# Generated by Django 5.2 on 2025-04-27 14:05

import django.db.models.deletion
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_citizen_recent_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship_photo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userauths.citizen')),
                ('citizenship_photo', models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_citizenship_pic_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='user_citizenship',
        ),
        migrations.AddField(
            model_name='citizen',
            name='user_recent_photo',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.citizen_recent_pic_path),
        ),
        migrations.DeleteModel(
            name='citizen_recent_photo',
        ),
    ]
