# Generated by Django 5.2 on 2025-04-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0018_citizenship_photo_remove_citizen_user_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenship_photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userauths.citizen'),
        ),
    ]
