# Generated by Django 5.2 on 2025-04-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0019_alter_citizenship_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship_photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='citizenship_photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.citizen'),
        ),
    ]
