# Generated by Django 5.2 on 2025-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0020_citizenship_photo_id_alter_citizenship_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='recent_photo_upload_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
