# Generated by Django 5.2 on 2025-04-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0021_citizen_recent_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='recent_photo_upload_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
