# Generated by Django 5.2 on 2025-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0023_citizen_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
