# Generated by Django 5.2 on 2025-04-30 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0024_alter_citizen_joined_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='joined_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
