# Generated by Django 5.2 on 2025-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0025_investigator_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
