# Generated by Django 5.2 on 2025-05-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0026_alter_investigator_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenship_photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.citizen'),
        ),
    ]
