# Generated by Django 5.2 on 2025-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0027_alter_citizenship_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
