# Generated by Django 5.1.6 on 2025-04-12 10:49

import Case.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '0014_investigator_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('wanted_id', models.AutoField(primary_key=True, serialize=False)),
                ('wanted_pic', models.ImageField(upload_to=Case.models.Wanted_pic_path)),
                ('wanted_name', models.CharField(max_length=100)),
                ('wanted_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('FIR_Registration', 'FIR Registration'), ('FIR_Verification', 'FIR Verification'), ('Investigator_Assigning', 'Investigator Assigning'), ('Investigation_Ongoing', 'Investigation Ongoing'), ('Investigation_Termination', 'Investigation Termination')], default='FIR_Registration', max_length=40)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('solved_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_reporter_the_victim', models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')])),
                ('crime_date', models.DateTimeField(blank=True, null=True)),
                ('crime_location', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_description', models.TextField(blank=True, null=True)),
                ('crime_time', models.TimeField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userauths.investigator')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userauths.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=500)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Case.case')),
            ],
        ),
    ]
