# Generated by Django 5.1.6 on 2025-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_wanted_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crime_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='crime_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
