# Generated by Django 5.1.6 on 2025-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_case_crime_link_alter_case_crime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(choices=[('ANTISOCIAL', 'Antisocial Behaviour'), ('BURGLARY', 'Burglary'), ('CRIMINAL_DAMAGE', 'Criminal Damage'), ('CYBERCRIME', 'CyberCrime'), ('FRAUD', 'Fraud'), ('HATE_CRIME', 'Hate Crime'), ('ROBBERY', 'Robbery'), ('RURAL_CRIME', 'Rural Crime'), ('SPIKING', 'Spiking'), ('STACKING', 'Stacking')], max_length=100),
        ),
    ]
