# Generated by Django 5.1.6 on 2025-04-15 08:06

import Case.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_alter_case_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_pic_file',
            field=models.ImageField(default=None, upload_to=Case.models.Evidence_pic_path),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_vid_file',
            field=models.FileField(default=None, upload_to=Case.models.Evidence_vid_path),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_reporter_the_victim',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
