# Generated by Django 5.2 on 2025-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0006_evidence_evidence_pic_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(choices=[('ANTI_SOCIAL', 'Antisocial Behaviour'), ('BURGLARY', 'Burglary'), ('CRIMINAL_DAMAGE', 'Criminal Damage'), ('CYBER_CRIME', 'CyberCrime'), ('FRAUD', 'Fraud'), ('HATE_CRIME', 'Hate Crime'), ('ROBBERY', 'Robbery'), ('RURAL_CRIME', 'Rural Crime'), ('SPIKING', 'Spiking'), ('STACKING', 'Stacking')], max_length=100),
        ),
    ]
