# Generated by Django 5.2 on 2025-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0007_alter_case_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='crime_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
