# Generated by Django 5.2 on 2025-05-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0008_alter_case_crime_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='solved_date',
            new_name='terminated_date',
        ),
    ]
