# Generated by Django 5.2 on 2025-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0009_rename_solved_date_case_terminated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='was_successful',
            field=models.BooleanField(default=False),
        ),
    ]
