# Generated by Django 5.2 on 2025-05-02 09:59

import Case.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0010_case_was_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_audio_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=Case.models.Evidence_audio_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_pic_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Case.models.Evidence_pic_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_vid_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=Case.models.Evidence_vid_path),
        ),
    ]
