# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0011_evidence_evidence_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_log',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity_log',
            name='activity_description',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='activity_log',
            name='activity_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
