# Generated by Django 5.2 on 2025-05-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0013_alter_activity_log_activity_title'),
        ('userauths', '0027_alter_citizenship_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.investigator'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.citizen'),
        ),
    ]
