# Generated by Django 5.2 on 2025-05-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0014_alter_case_investigator_alter_case_reporter'),
        ('userauths', '0028_citizen_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_by', to='userauths.investigator'),
        ),
    ]
