# Generated by Django 5.2 on 2025-05-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0015_case_registered_by'),
        ('userauths', '0028_citizen_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='uploaded_by_citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_activities', to='userauths.citizen'),
        ),
        migrations.AddField(
            model_name='activity_log',
            name='uploaded_by_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigator_activities', to='userauths.investigator'),
        ),
    ]
